pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                script {
                    // Checkout the source code from the repository
                    git 'https://github.com/your-username/your-repo.git'
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    // Build the project using Maven
                    sh 'mvn clean install'
                }
            }
        }

        // Add more stages as needed for testing, deployment, etc.
    }
}
